import { PrismaClient, CredentialStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Read the number from the command line arguments, default to 10
  const args = process.argv.slice(2);
  const numCredentials = parseInt(args[0], 10);
  
  const totalToSeed = isNaN(numCredentials) ? 10 : numCredentials;

  console.log(`Starting to seed ${totalToSeed} credentials...`);

  // Ensure at least one CredentialType exists
  let credentialType = await prisma.credentialType.findFirst();
  if (!credentialType) {
    credentialType = await prisma.credentialType.create({
      data: {
        code: `TYPE-${Date.now()}`,
        name: 'Default Credential Type',
        description: 'Autogenerated credential type for seeding'
      }
    });
    console.log(`Created default credential type: ${credentialType.name}`);
  }

  // Generate the specified number of credentials
  for (let i = 0; i < totalToSeed; i++) {
    const randomSuffix = Math.floor(Math.random() * 1000000000);
    const identityNumber = `ID-${Date.now()}-${randomSuffix}`;
    
    // 1. Create a dummy Person
    const person = await prisma.person.create({
      data: {
        firstName: `Test`,
        lastName: `Person ${i + 1}`,
        fullName: `Test Person ${i + 1} (${randomSuffix})`,
        typeIdentity: 'CC',
        identityNumber: identityNumber,
        birthDate: new Date('1990-01-01'),
        institutionalEmail: `test${i + 1}_${randomSuffix}@example.com`,
      }
    });

    // 2. Create the Credential associated with the Person
    const credential = await prisma.credential.create({
      data: {
        personId: person.id,
        credentialTypeId: credentialType.id,
        metadata: {
          rank: "Test Rank",
          unit: "Test Unit",
        },
        issueDate: new Date(),
        expirationDate: new Date(
          new Date().setFullYear(new Date().getFullYear() + 1),
        ),
        status: CredentialStatus.ACTIVE,
      },
    });

    console.log(`[${i + 1}/${totalToSeed}] Created credential ${credential.id} for ${person.fullName}`);
  }

  console.log(`Successfully seeded ${totalToSeed} credentials.`);
}

main()
  .catch((e) => {
    console.error('Error seeding credentials:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
